sudo: required

services:
  - docker

before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

env:
  global:
    - MIX_ENV=test
    - secure: St+IYGrfEeatjvk/fIsU6SdXRKhnU1pkxkMjgq4LJzsuoFbWYeRLd4Dc1l7djXHZYp7W5Lx7hFP3acFKH7Zmnn1dwSdQVjyyP618MjiCepAz/uiU+bVzOBuBoC7bBHzV19HpcafZxwxgNjQStX3kT4qIuUqu8GYaj/Op3rzjKhGMxTAT4LsMbBcl+kQOssXlRT37dlFMIowKSwvzftD4YUXSUa4cy3UHGuOgn3P1ii+KW/4PaZP9E1xLExMjMcxj+IFUJ54eKRF3Ar0p44eItTjp9dkuXK6FT8bGJWhwflsoEhPd0GvfK5urqLOw7frY97+0oSyOQkbG0J1CRNrpLwconCLT1aGprVa2E05yJsk6QuRBjUBog2eU8/oeqJkweg74MolUGaQiujJCgXVRq2W7xH6luSV95mHnaTOLSkdwZIw2giTKAqmv8bp5eiwHFfvlZwXhFshfDHPCobm3JcTn2HqzNWr+jDwexhV3N8Y0gXkDP6lOJJaUbc/LfbEFcXdHPmkM6fGgNHzGauZLv0SZqq383z6eabnFZW1qqZRvEE6QPaawgSK81jbACPIuW6z+7DCJI6wK3myyeUnszmI3WmhKm/+yFrrAkzMkxYiS0BOFR00qoAxUVRd/RCMctdhCeq2tfjsu7sMs1ooduDQfEh1e1NJW9Q6LsAkHaCc=

  matrix:
    - ES_VERSION=1.7.6
    - ES_VERSION=2.4.3
    - ES_VERSION=5.3.0

install:
  - docker-compose build

script:
  - docker-compose run app curl elasticsearch:9200
  - docker-compose run app mix coveralls.travis
